version: '3.6'

services:
  graphql-engine:
    image: hasura/graphql-engine:v2.43.0
    ports:
      - '8080:8080'
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      PG_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      HASURA_GRAPHQL_ENABLE_CONSOLE: '${HASURA_GRAPHQL_ENABLE_CONSOLE}'
      HASURA_GRAPHQL_DEV_MODE: '${HASURA_GRAPHQL_DEV_MODE}'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: '${HASURA_GRAPHQL_ENABLED_LOG_TYPES}'
      HASURA_EVENT_SECRET: '${HASURA_EVENT_SECRET}'
      HASURA_API_BASE_URL: '${HASURA_API_BASE_URL}'
      HASURA_GRAPHQL_ADMIN_SECRET: '${HASURA_GRAPHQL_ADMIN_SECRET}'
      HASURA_GRAPHQL_METADATA_DEFAULTS: '${HASURA_GRAPHQL_METADATA_DEFAULTS}'
    depends_on:
      data-connector-agent:
        condition: service_healthy

  data-connector-agent:
    image: hasura/graphql-data-connector:v2.43.0
    restart: always
    ports:
      - 8081:8081
    environment:
      QUARKUS_LOG_LEVEL: '${QUARKUS_LOG_LEVEL}'
      QUARKUS_OPENTELEMETRY_ENABLED: '${QUARKUS_OPENTELEMETRY_ENABLED}'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8081/api/v1/athena/health']
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s

volumes:
  db_data:
